# Generated by Django 2.0.3 on 2018-03-10 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('date_added', models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='date')),
                ('picture', models.ImageField(blank=True, upload_to='images', verbose_name='picture')),
            ],
        ),
    ]
