# Generated by Django 2.0.3 on 2018-03-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
